arquiproject/urls.py
# -*- coding: utf-8 -*-
from django.conf import settings
from django.conf.urls import include, patterns, url
from django.contrib import admin
from django.views.generic.base import RedirectView


urlpatterns = patterns(
    '',
    url(
        r'^admin/',
        include(admin.site.urls)
    ),
    url(
        r'',
        include('blog.urls', namespace='main')
    ),
    url(
        r'congreso/',
        include('congreso.urls', namespace='congreso')
    ),
    url(
        r'congreso/',
        include('congreso.urls', namespace='congreso')
    ),
    url(
        r'2do-congreso-nacional',
        RedirectView.as_view(
            pattern_name='congreso:home',
            permanent=False
        )
    ),
    url(
        r'^ckeditor/',
        include('ckeditor.urls')
    ),

    # Static files routes, only used when in debugging mode.
    url(
        r'^static/(?P<path>.*)$',
        'django.views.static.serve',
        {
            'document_root': settings.STATIC_ROOT
        }
    ),
    url(
        r'^media/(?P<path>.*)$',
        'django.views.static.serve',
        {
            'document_root': settings.MEDIA_ROOT
        }
    ),
)

handler404 = 'blog.views.e404'

blog/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import patterns, url
from django.views.generic import TemplateView

from .views import (
    NoticiaView, NoticiasView,
    SemblanzaView, SemblanzasView
)


urlpatterns = patterns(
    '',
    url(
        r'^$',
        'blog.views.index',
        name='index'
    ),
    url(
        r'^noticia/(?P<slug>[-\w]+)/$',
        NoticiaView.as_view(),
        name='noticia'
    ),
    url(
        r'^noticias/$',
        NoticiasView.as_view(),
        name='noticias'
    ),
    url(
        r'^historia/$',
        TemplateView.as_view(
            template_name='historia.html'
        ),
        name='historia'
    ),
    url(
        r'^mision-vision/$',
        TemplateView.as_view(
            template_name='mision-vision.html'
        ),
        name='mision_vision'
    ),
    url(
        r'^perfil-ingreso/$',
        TemplateView.as_view(
            template_name='perfil-ingreso.html'
        ),
        name='perfil_ingreso'
    ),
    url(
        r'^acreditacion/$',
        TemplateView.as_view(
            template_name='acreditacion.html'
        ),
        name='acreditacion'
    ),
    url(
        r'^objetivo-general/$',
        TemplateView.as_view(
            template_name='objetivo-general.html'
        ),
        name='objetivo_general'
    ),
    url(
        r'^campo-de-trabajo/$',
        TemplateView.as_view(
            template_name='campo-de-trabajo.html'
        ),
        name='campo_de_trabajo'
    ),
    url(
        r'^docentes/$',
        SemblanzasView.as_view(),
        name='docentes'
    ),
    url(
        r'^docente/(?P<slug>[-\w]+)/$',
        SemblanzaView.as_view(),
        name='docente'
    ),
)

congreso/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import patterns, url
from django.views.generic import TemplateView

from .views import (
    ConferencistaView, ConferencistasView,
    CursoView, CursosView,
    HomeView, RegistroCongresoCreateView, RegistroCursoCreateView,
    RegistroMesasDeDebateCreateView
)


urlpatterns = patterns(
    '',
    url(
        r'^home/$',
        HomeView.as_view(),
        name='home'
    ),
    url(
        r'^conferencistas/$',
        ConferencistasView.as_view(),
        name='conferencistas'
    ),
    url(
        r'^conferencistas/(?P<slug>[-\w]+)/$',
        ConferencistaView.as_view(),
        name='conferencista'
    ),
    url(
        r'^cursos/$',
        CursosView.as_view(),
        name='cursos'
    ),
    url(
        r'^cursos/(?P<slug>[-\w]+)/$',
        CursoView.as_view(),
        name='curso'
    ),
    url(
        r'^registro-curso/$',
        RegistroCursoCreateView.as_view(),
        name='registro_curso'
    ),
    url(
        r'^registro-congreso/$',
        RegistroCongresoCreateView.as_view(),
        name='registro_congreso'
    ),
    url(
        r'^registro-mesas-de-debate/$',
        RegistroMesasDeDebateCreateView.as_view(),
        name='registro_mesas_debate'
    ),
    url(
        r'^convocatoria/$',
        TemplateView.as_view(
            template_name='congreso/convocatoria.html'
        ),
        name='convocatoria'
    ),
)

templates/base.html
{% load staticfiles%}
  
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="description" content="">
        <meta name="author" content="">
        
        {% block titulo %}<title>{{ entrada.titulo }} Instituto tecnologico de Acapulco</title>{% endblock%}

        <!-- Bootstrap Core CSS -->
        <link rel="stylesheet" href="{% static 'css/fonts.css' %}" />
        <link rel="stylesheet" href="{% static 'css/full-slider.css' %}" />

        <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}"  />

        <!-- Custom CSS -->
        <link rel="stylesheet" href="{% static 'css/modern-business.css' %}"  />

        <!-- Custom Fonts -->
        <link href="{% static 'css/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet" type="text/css" />

        <link href="{% static 'css/custom.css' %}" rel="stylesheet" type="text/css" />
        {% block styles %}{% endblock styles %}
        <!--Used basically to load the proper meta tags for facebook.-->
        {% block meta_headers %}{% endblock%}

        <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
            <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
            <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
        <![endif]-->

    </head>
    <body>
        <!-- Navigation -->
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <header class="hidden-xs hidden-sm">
                <div class="container">
                    <div class="row">
                        <div class="col-xs-3">
                            <a href="/"><img class="logofederal" src="{% static 'imagenes/logo/logoheaderIzquierdo.png' %}" alt="logo de la sep federal"></a>
                        </div>
                        <div class="col-xs-6">
                            <h1>tecnológico nacional de méxico<br/>instituto tecnológico de acapulco</h1>
                        </div>
                        <div class="col-xs-3">
                            <a href="/"><img class="logoita" src="{% static 'imagenes/logo/tecnologico.png' %}" alt="logo tecnologico acapulco"></a>
                        </div>
                    </div>
                </div>
            </header>
            <div class="container">
                <!-- Brand and toggle get grouped for better mobile display -->
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    
                    <a href="{% url 'main:index' %}" class="logo"><img src="{% static 'imagenes/logo/Logo1.png' %}" width="200px"></a>
                </div>
                <!-- Collect the nav links, forms, and other content for toggling -->
               <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                    <ul class="nav navbar-nav navbar-right">
                        <li>
                            <a href="{% url 'main:index' %}">Inicio</a>
                        </li>
                        <li>
                            <a href="{% url 'main:acreditacion' %}">Acreditación</a>
                        </li>
                        <li>
                            <a href="{% url 'main:docentes' %}">Docentes</a>
                        </li>
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Alumnos<b class="caret"></b></a>
                            <ul class="dropdown-menu">
                                <li>
                                    <a href="portfolio-1-col.html">R. Profesionales</a>
                                </li>
                                <li>
                                    <a href="portfolio-2-col.html">Servicio Social</a>
                                </li>
                                <li>
                                    <a href="portfolio-3-col.html">Ret&iacute;cula</a>
                                </li>
                                <li>
                                    <a href="portfolio-4-col.html">SII</a>
                                </li>
                            </ul>
                        </li>
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Arquitectura <b class="caret"></b></a>
                            <ul class="dropdown-menu">
                                <li>
                                    <a href="{% url 'main:mision_vision' %}">Misión, Visión</a>
                                </li> 
                                <li>
                                       <a href="{% url 'main:historia' %}">Historia</a>
                                </li>
                                <li>
                                     <a href="{% url 'main:perfil_ingreso' %}">Perfil de ingreso, egreso</a>
                                </li>
                                <li>
                                     <a href="{% url 'main:objetivo_general' %}">Objetivo general</a>
                                </li>
                                <li>
                                     <a href="{% url 'main:campo_de_trabajo' %}">Campo de trabajo</a>
                                </li>
                            </ul>
                        </li>
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Congreso anual<b class="caret"></b></a>
                            <ul class="dropdown-menu">
                                <li>
                                    <a href="{% url 'congreso:home' %}">Registro Congreso</a>
                                </li> 
                                <li>
                                    <a href="{% url 'congreso:conferencistas' %}">Conferencistas</a>
                                </li>
                                <li>
                                    <a href="{% url 'congreso:cursos' %}">Cursos taller</a>
                                </li>
                            </ul>
                        </li>
                    </ul>
                </div>
                <!-- /.navbar-collapse -->
            </div>
            <!-- /.container -->
        </nav>
        <div id="main-content">
        {% include "common/messages.html" %}
        </div>

        {% block contenido%} {%endblock%}
        <div class="container-fluid">
            <div class="row">
                <hr>
                <div class="col-xs-3 col-sm-4">
                    <hr>
                    <hr>
                </div>
                    <div class="col-xs-6 col-sm-4 text-center">
                        <img class="footer1"src="{% static 'imagenes/logo/logosep.png' %}" width="200px">
                    </div>

                        <div class="col-xs-3 col-sm-4">
                            <hr>
                            <hr>
                        </div>
                            <div class="col-xs-12">
                        <hr>
                    </div>
                </div>

                <!-- Footer -->
                <footer>
                    <div class="row">
                        <div class="col-lg-12">
                            <p class="text-center">Copyright &copy; Avenida Instituto Tecnológico S/N, Crucero del Cayaco C.P. 39905, Teléfono: 01(744) 442 9011 ext 147, Correo electrónico: arquitecutra.ita@gmail.com.</p>
                        </div>
                    </div>
                </footer>

            </div>
        </div>

        <!-- jQuery -->
        <script src="{% static 'js/jquery.js' %}"></script>

        <!-- Bootstrap Core JavaScript -->
        <script src="{% static 'js/bootstrap.min.js' %}"></script>

        {% block scripts %} {% endblock scripts %}

        <!-- Script to Activate the Carousel -->
       <script>
        $(document).ready(function(){
            $('.myCarousel').carousel({
                interval: 5000
            });
        });
    </script>

    </body>
</html>

templates/campo-de-trabajo.html
{% extends "base.html" %}
{% load staticfiles %}

{% block titulo %}<title>Campo de trabajo - Instituto Tecnológico de Acapulco</title>{% endblock%}
{% block contenido%}
    <div class="row">
        <br><br>
        <div class="text-center" >
            <img class="ntodas" alt="Campo de trabajo" src="{% static 'imagenes/imagenes/campo_de_trabajo.jpg' %}" />	
        </div>	

        <div class="text-justify1 margin-top-low" >

            <h3 class="text-red">CAMPO DE TRABAJO</h3>
            <p>
                El arquitecto es el profesional que asume la responsabilidad de 
                proyectar y construir los espacios habitables que necesita la sociedad, 
                incluyendo aspectos físicos y culturales. Su trabajo surge a partir 
                de las necesidades de la sociedad, en este sentido debe promover 
                los medios para cubrir esas expectativas sin deteriorar el 
                contexto cultural y ecológico.
            </p>
            <br>
        </div>	
    </div>	
{% endblock%}

templates/construccion.html
{% extends "base.html" %}
{% load staticfiles %}
{% block contenido%} 

    <!-- Page Content -->
    <div class="container">

        <!-- Page Heading/Breadcrumbs -->
        <div class="row">
            <div class="col-lg-12">
                <h1 class="page-header">
                    <small>P&aacute;gina en construccion </small>
                </h1>
                <ol class="breadcrumb">
                    <li><a href="{% url 'main:index' %}">Inicio</a>
                    </li>
                    <li class="active"></li>
                </ol>
            </div>
        </div>
        <!-- /.row -->

        <div class="row">

            <div class="col-lg-12">
                <div class="jumbotron">
                    <h1><span class="error-404"></span>
                   

                     <div class=".col-xs .col-sm-4">
                    <img src="{% static 'imagenes/imagenes/cons.jpg' %}" class="img-responsive">

                    </h1>
                        </div>
                    </div>
                        

                    </div>
                </div>
            </div>
        </div>
        



  {%endblock%}

templates/docente.html
{% extends "base.html" %}
{% load staticfiles %}
{% load thumbnail %}

{% block titulo %}<title>{{ semblanza.nombre }} - Instituto Tecnológico de Acapulco</title>{% endblock%}
{% block contenido%}
    <br/>
    <br/>
    <div class="row">
        <div class="text-justify1 margin-top-low" >

            <h3 class="text-red">{{ semblanza.nombre }}</h3>
            <h4 class="text-red">Semblanza</h4>
            <div class="row">
                <div class="col-sm-3 text-center">
                    {% thumbnail semblanza.imagen "300x300" crop="center" as im %}
                    <img
                        class="rounded-avatar-image"
                        src="{{ im.url }}"
                        alt="{{ semblanza.nombre }}"
                        title="{{ semblanza.nombre }}" />
                    {% endthumbnail %}
                </div>
                <div class="col-sm-9 text-justify">
                    {{ semblanza.contenido|safe }}
                </div>
            </div>
            <br>
        </div>  
    </div>  
{% endblock%}

templates/docentes.html
{% extends "base.html" %}
{% load staticfiles %}
{% load thumbnail %}

{% block titulo %}<title>Docentes - Instituto Tecnológico de Acapulco</title>{% endblock%}
{% block contenido%}
    <div class="row">
        <br><br>
        <div class="text-center" >
            <img class="ntodas" alt="Mision y Vision" src="{% static 'imagenes/imagenes/maestros.jpg' %}" />	
        </div>	

        <div class="text-justify1 margin-top-low" >

            <h3 class="text-red">DOCENTES</h3>
            <h4 class="text-red">SEMBLANZAS</h4>
            {% if semblanzas %}
                <div class="row">
                    {% for semblanza in semblanzas %}
                    <div class="col-sm-3">
                        <a href="{% url 'main:docente' semblanza.slug%}">
                            <div class="thumbnail">

                                {% thumbnail semblanza.imagen "300x300" crop="center" as im %}
                                <img
                                    class="rounded-avatar-image"
                                    src="{{ im.url }}"
                                    alt="{{ semblanza.nombre }}"
                                    title="{{ semblanza.nombre }}" />
                                {% endthumbnail %}

                                <div class="caption">
                                    <h5 class="text-center"><strong>{{ semblanza.nombre }}</strong></h5>
                                </div>
                            </div>
                        </a>
                    </div>
                    {% endfor %}
                </div>
            {% else %}
                No hay docentes que mostrar.
            {% endif %}
            <br>
        </div>	
    </div>	
{% endblock%}

templates/index.html
{% extends "base.html" %}
{% load staticfiles %}
{% load thumbnail %}

{% block styles %}
{% endblock styles %}

{% block contenido%}
    <!-- Header Carousel -->
    <header id="myCarousel" class="carousel slide">
        <div id="Carousel">
    
        <!-- Indicators -->
        <ol class="carousel-indicators">
        {% for slide in  slides %}
                {% if forloop.first %}
                        <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
                {% else %}
            <li data-target="#carousel-example-generic" data-slide-to="1"></li>
            {% endif%}
        {%endfor%}

        </ol>

        <!-- Wrapper for slides -->
       
        <div class="carousel-inner">
        {% for slide in  slides %}
                {% if forloop.first %}
            <div class="item active">
                {% else %}
                    <div class="item">
                {%endif%}

                {% thumbnail slide.imagen "1700x675" crop="center" as im %}
                <img
                    src="{{ im.url }}"
                    class="ntodas"
                    alt="{{ slide.titulo }}" />
                {% endthumbnail %}

               {% if slide.titulo|length > 0 %}
                <div class="carousel-caption">
                    <h2>{{ slide.titulo }}</h2>
                </div>
                {% endif %}
            </div>
        {% endfor %}
        </div>
       
        <a class="left carousel-control" href="#myCarousel" data-slide="prev">
            <span class="icon-prev"></span>
        </a>
                <a class="right carousel-control" href="#myCarousel" data-slide="next">
            <span class="icon-next"></span>
        </a>

    </div>
        </div>

    </header>

    <!-- Page Content -->
    <div class="container">

        <!-- Marketing Icons Section -->
        <div class="row">
           <div class="text-center col-lg-12 quote">
                <h2 class="page-header">
                    "La Arquitectura debe hablar de su tiempo y su lugar, <br>
                    a la vez, anhelar la eternidad"
                </h2>
                <h3 class="red-text">Frank Gehry - Arquitecto</h3>
            </div>
        </div>
        <!-- /.row -->

        <!-- Portfolio Section -->
        <div class="row">
            <div class="text-center col-lg-12">
                <h2 class="page-header">Publicaciones</h2>
            </div>
           <!-- Page Features -->
        {% for entrada in  entradas %}
            <div class="col-md-4 text-center" >
             <a href="{% url 'main:noticia' entrada.slug %}">
                <div class="thumbnail post">
                <span class="news-date"><h5>{{ entrada.time|date:"d M " }}</h5></span>

                {% thumbnail entrada.imagen "750x400" crop="center" as im %}
                <img src="{{ im.url }}" alt="" />
                {% endthumbnail %}
                    
                    <div class="caption">
                
                        <h3>{{ entrada.titulo }} <br></h3>
                        <h4><small>Publicado: {{ entrada.time}}</small></h4>
                       <h5> <p>{{ entrada.resumen }}</p></h5>
                    </div>
                </div>
                </a>
            </div>

            {% endfor %}
        </div>

        <br>
    <div class="row">
        <div class="text-center">
            <a href="{% url 'main:noticias' %}" class="btn btn-primary" role="button">VER TODAS LAS PUBLICACIONES</a>
        </div>
    </div>
{% endblock%}

{% block scripts %}
{% endblock scripts %}

templates/mision-vision.html
{% extends "base.html" %}
{% load staticfiles %}

{% block titulo %}<title>Misión, Visión y Valores - Instituto Tecnológico de Acapulco</title>{% endblock%}
{% block contenido%}
    <div class="row">
        <br><br>
        <div class="text-center" >
            <img class="ntodas" alt="Mision y Vision" src="{% static 'imagenes/imagenes/mision-vision.jpg' %}" />	
        </div>	

        <div class="text-justify1 margin-top-low" >

            <h3 class="text-red">MISIÓN</h3>

            <p>Coadyuvar al desarrollo integral de la sociedad, a través de la formación académica y humana de profesionales de la arquitectura en consistencia con nuestras raíces culturales y principios ecológicos fundamentales.</p>

            <p>Con un alto sentido de compromiso social y de la ética, de mente abierta, competente y creativo.</p>

            <h3 class="text-red">VISIÓN</h3>
            <p>Aspiramos a ser una escuela de arquitectura vanguardista con un alto nivel académico y de servicio social, reconocida a nivel nacional, con egresados competentes, docentes actualizados y comprometidos. </p>


            <h3 class="text-red">OBJETIVO GENERAL</h3>

            <P>Formar profesionistas líderes con excelencia académica y humanística capaces de diseñar y construir el hábitat humano y participar en la toma de decisiones inherentes al mismo, con vocación de servicio a la sociedad, dentro de un marco de sustentabilidad.</P>


            <h3 class="text-red">VALORES</h3>

            <p>En los programas académicos del Instituto Tecnológico de Acapulco, se promoverán los valores siguientes:</p>

            <ul>
                    <li>Verdad, equidad y justicia</li>
                    <li>Libertad de Pensamiento</li>
                    <li>Sensibilidad y creatividad</li>
                    <li>Trabajo Honesto, productivo y perseverante</li>
                    <li>Responsabilidad</li>
                    <li>Competitividad.</li>
            </ul>
            <br>
        </div>	
    </div>	
{% endblock%}

templates/noticia.html
{% extends "base.html" %}
{% load staticfiles %}
{% load thumbnail %}

{% block meta_headers %}
    <meta property="fb:app_id" content="100599273677056" />
    <meta property="og:type" content="website" /> 
    <meta property="og:url" content="http://ita-arquitectura.com/noticia/{{ entrada.slug }}/" /> 
    <meta property="og:title"  content="{{ entrada.titulo  }} | Instituto Tecnológico de Acapulco" />
    {% if entrada.imagen %}
        {% thumbnail entrada.imagen "730x380" crop="center" as im %}
        <meta property="og:image" content="http://ita-arquitectura.com{{ im.url }}" />
        {% endthumbnail %}
    {% endif %}
{% endblock meta_headers %}
   
{% block contenido%}
    <!-- Page Content -->
    <div class="container">

        <!-- Page Heading/Breadcrumbs -->
        <div class="row">
            <div class="col-lg-12">
               
               <br><br><br> <ol class="breadcrumb">

                   <li><a href="{% url 'main:index' %}">Ir a inicio</a>
                    </li>
                    <li><a href="{% url 'main:noticias' %}">Ver todas las publicaciones</a>
                    </li>
                    <li class="active"></li>
                </ol>
                <h1 class="page-header">{{ entrada.titulo }}
                    </h1>

            </div>
        </div>
        <!-- /.row -->

        <!-- Portfolio Item Row -->
        <div class="row">

            <div class="col-md-8">
                
                    <!-- Wrapper for slides -->
                    <div class="carousel-inner">
                        <div class="item active">
                        {% thumbnail entrada.imagen "730x380" crop="center" as im %}
                            <img src="{{ im.url }}" />
                        {% endthumbnail %}
                        
                        </div>
                        <br>
                       
                   </div>
            </div>
                <p><strong><span class="glyphicon glyphicon-time icon-styles"></span> Publicado: {{ entrada.time }}</strong></p>
                <p>{{ entrada.contenido| safe }}</p>
          </div>

        <div class="row">
            {% if entrada.archivos %}
                <hr>
                <h4>Archivos</h4>
                {% for archivo in entrada.archivos %}
                    {% if forloop.first %}
                        <hr>
                    {% endif %}
                    <div class="margin-top-low">
                        <a target="_blank" class="text-green link" href="{{ archivo.archivo.url }}">
                            <span class="glyphicon glyphicon-paperclip icon-styles"></span>
                            {{ archivo.descripcionArchivo }}
                        </a>
                    </div>
                {% endfor %}
            {% endif %}
            
            {% if entrada.videos %}
                <hr>
                <h4>Videos</h4>
                {% for video in entrada.videos %}
                    {% if forloop.first %}
                        <hr>
                    {% endif %}
                    <h5>
                        <span class="glyphicon glyphicon-play-circle icon-styles icon-video"></span>
                        {{ video.descripcionVideoYoutube }}
                    </h5>
                    <div class="embed-responsive embed-responsive-16by9">
                      <iframe class="embed-responsive-item"  src="//www.youtube.com/embed/{{ video.claveYoutube }}" ></iframe>
                    </div>      
                {% endfor %}
            {% endif %}
        </div>
        <!-- /.row -->
         <hr>
      <div id="disqus_thread"></div>
    <script type="text/javascript">
        /* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
             var disqus_shortname = 'arquitecturaita'; // required: replace example with your forum shortname

                /* * * DON'T EDIT BELOW THIS LINE * * */
                 (function() {
                        var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
                                dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
                                    (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
                            })();
                         </script>
                    <noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript"></a></noscript>
    
{% include 'nrelacionadas.html'%}
       
{% endblock %}

templates/noticias.html
{% extends "base.html" %}
{% load staticfiles %}
{% load thumbnail %}

  {% block contenido%}
    <!-- Page Content -->
    <div class="container">

        <!-- Page Heading/Breadcrumbs -->
        <div class="row">
            <div class="col-lg-12">
                <h1 class="page-header">Publicaciones</h1>
                <ol class="breadcrumb">
                    <li><a href="{% url 'main:index' %}">Inicio</a>
                    </li>
                    <li class="active">Todas las publicaciones</li>
                </ol>
            </div>
        </div>
        <!-- /.row -->

        <!-- Project One -->
         {% for entrada in object_list %}
         

        <div class="row">
            <div class="col-md-7">
                <a href="{% url 'main:noticia' entrada.slug %}">
                     
                {% thumbnail entrada.imagen "600x250" crop="center" as im %}
                    <img class="ntodas" src="{{ im.url }}" alt="" />
                {% endthumbnail %}
                </a>
            </div>
            <div class="col-md-5">
                <h3>{{ entrada.titulo}}</h3>
                <p>publicado: {{ entrada.time |date:"d M Y"}}</p>
                <p>{{ entrada.resumen}}</p>
                
                <a class="btn btn-primary" href="{% url 'main:noticia' entrada.slug %}">Leer más</i></a>
            </div>
        </div>
        <!-- /.row -->
    
        <hr>
        {% endfor %}

        <!-- Pagination -->
        <div class="row text-center">
            <div class="col-lg-12">
                <ul class="pagination">
                    <li>
                        <a href="#">&laquo;</a>
                    </li>
                    <li class="active">
                        <a href="#">1</a>
                    </li>
                    <li>
                        <a href="#">2</a>
                    </li>
                    <li>
                        <a href="#">3</a>
                    </li>
                    <li>
                        <a href="#">4</a>
                    </li>
                    <li>
                        <a href="#">5</a>
                    </li>
                    <li>
                        <a href="#">&raquo;</a>
                    </li>
                </ul>
            </div>
        </div>
        <!-- /.row -->
        
        {% endblock %}