arquiproject/urls.py
# -*- coding: utf-8 -*-
from django.conf import settings
from django.conf.urls import include, patterns, url
from django.contrib import admin
from django.views.generic.base import RedirectView


urlpatterns = patterns(
    '',
    url(
        r'^admin/',
        include(admin.site.urls)
    ),
    url(
        r'',
        include('blog.urls', namespace='main')
    ),
    url(
        r'congreso/',
        include('congreso.urls', namespace='congreso')
    ),
    url(
        r'congreso/',
        include('congreso.urls', namespace='congreso')
    ),
    url(
        r'2do-congreso-nacional',
        RedirectView.as_view(
            pattern_name='congreso:home',
            permanent=False
        )
    ),
    url(
        r'^ckeditor/',
        include('ckeditor.urls')
    ),

    # Static files routes, only used when in debugging mode.
    url(
        r'^static/(?P<path>.*)$',
        'django.views.static.serve',
        {
            'document_root': settings.STATIC_ROOT
        }
    ),
    url(
        r'^media/(?P<path>.*)$',
        'django.views.static.serve',
        {
            'document_root': settings.MEDIA_ROOT
        }
    ),
)

handler404 = 'blog.views.e404'

blog/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import patterns, url
from django.views.generic import TemplateView

from .views import (
    NoticiaView, NoticiasView,
    SemblanzaView, SemblanzasView
)


urlpatterns = patterns(
    '',
    url(
        r'^$',
        'blog.views.index',
        name='index'
    ),
    url(
        r'^noticia/(?P<slug>[-\w]+)/$',
        NoticiaView.as_view(),
        name='noticia'
    ),
    url(
        r'^noticias/$',
        NoticiasView.as_view(),
        name='noticias'
    ),
    url(
        r'^historia/$',
        TemplateView.as_view(
            template_name='historia.html'
        ),
        name='historia'
    ),
    url(
        r'^mision-vision/$',
        TemplateView.as_view(
            template_name='mision-vision.html'
        ),
        name='mision_vision'
    ),
    url(
        r'^perfil-ingreso/$',
        TemplateView.as_view(
            template_name='perfil-ingreso.html'
        ),
        name='perfil_ingreso'
    ),
    url(
        r'^acreditacion/$',
        TemplateView.as_view(
            template_name='acreditacion.html'
        ),
        name='acreditacion'
    ),
    url(
        r'^objetivo-general/$',
        TemplateView.as_view(
            template_name='objetivo-general.html'
        ),
        name='objetivo_general'
    ),
    url(
        r'^campo-de-trabajo/$',
        TemplateView.as_view(
            template_name='campo-de-trabajo.html'
        ),
        name='campo_de_trabajo'
    ),
    url(
        r'^docentes/$',
        SemblanzasView.as_view(),
        name='docentes'
    ),
    url(
        r'^docente/(?P<slug>[-\w]+)/$',
        SemblanzaView.as_view(),
        name='docente'
    ),
)

congreso/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import patterns, url
from django.views.generic import TemplateView

from .views import (
    ConferencistaView, ConferencistasView,
    CursoView, CursosView,
    HomeView, RegistroCongresoCreateView, RegistroCursoCreateView,
    RegistroMesasDeDebateCreateView
)


urlpatterns = patterns(
    '',
    url(
        r'^home/$',
        HomeView.as_view(),
        name='home'
    ),
    url(
        r'^conferencistas/$',
        ConferencistasView.as_view(),
        name='conferencistas'
    ),
    url(
        r'^conferencistas/(?P<slug>[-\w]+)/$',
        ConferencistaView.as_view(),
        name='conferencista'
    ),
    url(
        r'^cursos/$',
        CursosView.as_view(),
        name='cursos'
    ),
    url(
        r'^cursos/(?P<slug>[-\w]+)/$',
        CursoView.as_view(),
        name='curso'
    ),
    url(
        r'^registro-curso/$',
        RegistroCursoCreateView.as_view(),
        name='registro_curso'
    ),
    url(
        r'^registro-congreso/$',
        RegistroCongresoCreateView.as_view(),
        name='registro_congreso'
    ),
    url(
        r'^registro-mesas-de-debate/$',
        RegistroMesasDeDebateCreateView.as_view(),
        name='registro_mesas_debate'
    ),
    url(
        r'^convocatoria/$',
        TemplateView.as_view(
            template_name='congreso/convocatoria.html'
        ),
        name='convocatoria'
    ),
)

congreso/models.py
# -*- coding: utf-8 -*-
from ckeditor.fields import RichTextField

from django.db import models
from django.template.defaultfilters import slugify


class Curso(models.Model):
    imagen = models.ImageField(
        upload_to='cursos',
        help_text='Imagen de curso/taller.'
    )
    nombre = models.CharField(
        max_length=150
    )
    dias_horario = models.CharField(
        max_length=200,
        blank=True,
        null=True,
        help_text=u'Dias y horario en los que se impartirá el curso.'
    )
    contenido = RichTextField()
    activo = models.BooleanField(
        default=True
    )
    slug = models.SlugField(
        editable=False,
        max_length=150
    )

    def __unicode__(self):
        return u'{}'.format(self.nombre)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.nombre.encode('utf-8'))
        super(Curso, self).save(*args, **kwargs)


class Conferencista(models.Model):
    imagen = models.ImageField(
        upload_to='conferencistas',
        help_text='Imagen del conferencista.'
    )
    nombre = models.CharField(
        max_length=100
    )
    contenido = RichTextField()
    activo = models.BooleanField(
        default=True
    )
    slug = models.SlugField(
        editable=False,
        max_length=150
    )

    def __unicode__(self):
        return u'{}'.format(self.nombre)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.nombre.encode('utf-8'))
        super(Conferencista, self).save(*args, **kwargs)


class Obra(models.Model):
    """
    Obra correspondiente a un conferencista.
    """
    imagen = models.ImageField(
        upload_to='obras',
        help_text='Imagen de obra del conferencista.'
    )
    contenido = RichTextField()

    conferencista = models.ForeignKey(
        Conferencista,
        related_name='obras'
    )


class BaseRegister(models.Model):
    """
    Modelo base, usado para los registros del congreso.
    """
    nombre = models.CharField(
        max_length=100
    )
    apellido_paterno = models.CharField(
        max_length=50
    )
    apellido_materno = models.CharField(
        max_length=50
    )
    numero_control = models.IntegerField(
        blank=True,
        null=True
    )
    correo_electronico = models.EmailField()
    escuela_de_procedencia = models.CharField(
        max_length=50
    )

    es_alumno_ITA = models.BooleanField(default=False)
    folio_recibo_oficial = models.CharField(
        max_length=50,
        null=True,
        blank=True
    )

    estado_municipio = models.CharField(
        max_length=50,
        verbose_name="Estado y Municipio de Procedencia"
    )
    clave_de_registro = models.CharField(
        max_length=8,
        unique=True,
        editable=False
    )
    es_valido = models.BooleanField(
        blank=True,
        default=False
    )

    @property
    def nombre_completo(self):
        return u' '.join([
            self.nombre,
            self.apellido_paterno,
            self.apellido_materno,
        ])

    def __unicode__(self):
        return u'Registro de {}'.format(self.nombre_completo)

    class Meta:
        abstract = True


class RegistroCurso(BaseRegister):
    """
    Formulario de registro para cursos-taller.
    """
    curso = models.ForeignKey(Curso)

    class Meta:
        verbose_name = u'Registro de curso'
        verbose_name_plural = u'Registros de curso'


class RegistroCongreso(BaseRegister):
    """
    Formulario de registro para el congreso.
    """
    TIPOS_INSCRIPCION = (
        ('esita', u'Alumnos y Ex Alumnos ITA ($500.00)'),
        ('eotra', u'Alumnos otras Instituciones ($700.00)'),
        ('profe', u'Profesionistas y público en general ($950.00)'),
    )
    tipo_de_inscripcion = models.CharField(
        max_length=5,
        choices=TIPOS_INSCRIPCION,
    )

    class Meta:
        verbose_name = u'Registro de congreso'
        verbose_name_plural = u'Registros de congreso'


class RegistroMesasDeDebate(BaseRegister):
    """
    Formulario de registro para las mesas de debate.
    """
    archivo_sintesis = models.FileField(
        upload_to='archivosintesis',
        null=True,
        blank=True
    )

    class Meta:
        verbose_name = u'Registro de mesas de debate'
        verbose_name_plural = u'Registros de mesas de debate'

congreso/forms.py
# -*- coding: utf-8 -*-
from django import forms
from django.forms import ModelForm

from .models import RegistroCongreso, RegistroCurso, RegistroMesasDeDebate


class RegistroCursoForm(ModelForm):
    class Meta:
        model = RegistroCurso
        fields = [
            'nombre',
            'apellido_paterno',
            'apellido_materno',
            'numero_control',
            'correo_electronico',
            'escuela_de_procedencia',
            'folio_recibo_oficial',
            'estado_municipio',
            'curso',
        ]

    def clean(self):
        cleaned_data = super(RegistroCursoForm, self).clean()
        #
        # Checking if there is available spaces to being registered
        # to the course.
        #
        course_register_limit = 30
        if 'curso' in cleaned_data:
            course = cleaned_data['curso']
            course_registers_count = RegistroCurso.objects.filter(
                curso=course
            ).count()

            if not course_registers_count < course_register_limit:
                raise forms.ValidationError(
                    'Se ha alcanzado el cupo máximo de '
                    '<strong>{0} espacios</strong> para el curso '
                    '<strong>"{1}"</strong>, por favor intenta con otro '
                    'curso de tu interés.'.format(
                        course_register_limit,
                        course.nombre.encode('utf-8')
                    )
                )

        return cleaned_data


class RegistroCongresoForm(ModelForm):
    class Meta:
        model = RegistroCongreso
        fields = [
            'nombre',
            'apellido_paterno',
            'apellido_materno',
            'numero_control',
            'correo_electronico',
            'escuela_de_procedencia',
            'folio_recibo_oficial',
            'estado_municipio',
            'tipo_de_inscripcion',
        ]

    def clean(self):
        cleaned_data = super(RegistroCongresoForm, self).clean()
        #
        # Checking if there is available spaces to being registered
        # to the congress.
        #
        congress_register_limit = 900
        congress_registers_count = RegistroCongreso.objects.all().count()

        if not congress_registers_count < congress_register_limit:
            raise forms.ValidationError(
                'Se ha alcanzado el cupo máximo de '
                '<strong>{0} espacios</strong> para el congreso, no fue '
                'posible completar el registro.'.format(
                    congress_register_limit
                )
            )

        return cleaned_data


class RegistroMesasDeDebateForm(ModelForm):
    class Meta:
        model = RegistroMesasDeDebate
        fields = [
            'nombre',
            'apellido_paterno',
            'apellido_materno',
            'numero_control',
            'correo_electronico',
            'escuela_de_procedencia',
            'folio_recibo_oficial',
            'estado_municipio',
            'archivo_sintesis',
        ]

    def clean(self):
        cleaned_data = super(RegistroMesasDeDebateForm, self).clean()
        #
        # Checking if there is available spaces to being registered
        # to the discussion tables.
        #
        discussions_register_limit = 100
        discussions_registers_count = (
            RegistroMesasDeDebate.objects.all().count()
        )

        if not discussions_registers_count < discussions_register_limit:
            raise forms.ValidationError(
                'Se ha alcanzado el cupo máximo de '
                '<strong>{0} espacios</strong> para las mesas de debate,'
                ' no fue posible completar el registro.'.format(
                    discussions_register_limit
                )
            )

        return cleaned_data

congreso/views.py
# -*- coding: utf-8 -*-
import random
from hashlib import md5

from django.contrib.messages.views import SuccessMessageMixin
from django.core.urlresolvers import reverse_lazy
from django.views.generic import DetailView, ListView
from django.views.generic.edit import CreateView

from .forms import (
    RegistroCongresoForm, RegistroCursoForm,
    RegistroMesasDeDebateForm
)
from .models import (
    Conferencista, Curso,
    RegistroCongreso, RegistroCurso, RegistroMesasDeDebate
)


class HomeView(ListView):
    queryset = Conferencista.objects.filter(
        activo=True
    ).order_by(
        'nombre'
    )
    context_object_name = 'conferencistas'
    template_name = 'congreso/home.html'

    def get_context_data(self, **kwargs):
        context = super(HomeView, self).get_context_data(**kwargs)
        context['cursos'] = Curso.objects.filter(
            activo=True
        ).order_by(
            'nombre'
        )[:6]
        return context


class ConferencistasView(ListView):
    queryset = Conferencista.objects.filter(
        activo=True
    ).order_by(
        'nombre'
    )
    context_object_name = 'conferencistas'
    template_name = 'congreso/conferencistas/list.html'


class ConferencistaView(DetailView):
    queryset = Conferencista.objects.filter(
        activo=True
    )
    context_object_name = 'conferencista'
    template_name = 'congreso/conferencistas/detail.html'


class CursosView(ListView):
    queryset = Curso.objects.filter(
        activo=True
    ).order_by(
        'nombre'
    )
    context_object_name = 'cursos'
    template_name = 'congreso/cursos/list.html'

    def get_context_data(self, **kwargs):
        context = super(CursosView, self).get_context_data(**kwargs)
        context['form'] = RegistroCursoForm()
        return context


class CursoView(DetailView):
    queryset = Curso.objects.filter(
        activo=True
    )
    context_object_name = 'curso'
    template_name = 'congreso/cursos/detail.html'


class BaseRegisterCreateView(SuccessMessageMixin, CreateView):

    def generate_register_key(self, instance):
        unique_data = "{0}{1}{2}{3}{4}{5}".format(
            instance.nombre.encode('utf-8'),
            instance.apellido_paterno.encode('utf-8'),
            instance.apellido_materno.encode('utf-8'),
            instance.correo_electronico.encode('utf-8'),
            instance.escuela_de_procedencia.encode('utf-8'),
            random.randint(0, 10000000)
        )
        dirty_key = md5(unique_data).hexdigest()
        return (dirty_key[:8]).upper()

    def form_valid(self, form):
        self.register_key = self.generate_register_key(form.instance)
        form.instance.clave_de_registro = self.register_key

        form.instance.nombre = form.instance.nombre.upper()
        form.instance.apellido_paterno = form.instance.apellido_paterno.upper()
        form.instance.apellido_materno = form.instance.apellido_materno.upper()

        return super(BaseRegisterCreateView, self).form_valid(form)

    def get_success_message(self, cleaned_data):
        return self.dirty_success_message.format(
            cleaned_data['nombre'].encode('utf-8'),
            self.register_key
        )


class RegistroCursoCreateView(BaseRegisterCreateView):
    model = RegistroCurso
    form_class = RegistroCursoForm
    success_url = reverse_lazy('congreso:cursos')
    template_name = "congreso/cursos/create.html"
    dirty_success_message = (
        'Felicidades <strong>{0}</strong>! has sido registrado '
        'exitosamente al curso "<strong>{1}</strong>". '
        'Tu clave de registro es: <strong>{2}</strong>'
    )

    def get_success_message(self, cleaned_data):
        return self.dirty_success_message.format(
            cleaned_data['nombre'].encode('utf-8'),
            cleaned_data['curso'].nombre.encode('utf-8'),
            self.register_key
        )


class RegistroCongresoCreateView(BaseRegisterCreateView):
    model = RegistroCongreso
    form_class = RegistroCongresoForm
    success_url = reverse_lazy('congreso:home')
    template_name = "congreso/congreso/create.html"
    dirty_success_message = (
        'Felicidades <strong>{0}</strong>! has sido registrado '
        'exitosamente al <strong>Congreso</strong>. '
        'Tu clave de registro es: <strong>{1}</strong>'
    )


class RegistroMesasDeDebateCreateView(BaseRegisterCreateView):
    model = RegistroMesasDeDebate
    form_class = RegistroMesasDeDebateForm
    success_url = reverse_lazy('congreso:home')
    template_name = "congreso/mesasdebate/create.html"
    dirty_success_message = (
        'Felicidades <strong>{0}</strong>! has sido registrado '
        'exitosamente a las <strong>Mesas de debate</strong>. '
        'Tu clave de registro es: <strong>{1}</strong>'
    )

templates/congreso/curso.html
{% extends "base.html" %}
{% load staticfiles %}
{% load thumbnail %}

{% block contenido%}
    <!-- Page Content -->
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <br><br><br>
                <h1 class="page-header">{{ curso.nombre }}</h1>
            </div>
        </div>

        <div class="row">
            <div class="col-md-12">
                <div class="carousel-inner">
                    <div class="item active">
                    {% thumbnail curso.imagen "730x200" crop="center" as im %}
                        <img src="{{ im.url }}" class="responsive-img" />
                    {% endthumbnail %}
                    </div>
                    <br>
                </div>
            </div>
            <h5>
                <strong>
                    <span class="glyphicon glyphicon-time icon-styles"></span>
                    Dias y horario: 
                    {% if curso.dias_horario%}
                        {{ curso.dias_horario }}
                    {% else %}
                        No disponible
                    {% endif %}
                </strong>
            </h5>
            <p>{{ curso.contenido| safe }}</p>
        </div>
    </div>
    {% include 'congreso/partials/register-to-course-sticky-button.html' %}
{% endblock %}

templates/congreso/home.html
{% extends "base.html" %}
{% load staticfiles %}
{% load thumbnail %}

{% block titulo %}<title>Convocatoria - Instituto Tecnológico de Acapulco</title>{% endblock%}
{% block contenido%}
<div class="convocatoria">
    <div class="convocatoria-background">
        <img src="{% static 'imagenes/congreso/convocatoria_background.jpg'%}" alt="">
    </div>	
    <div class="container-fluid dark-jumbotron">
        <div class="container-fluid">
            <div class="text-center padding-top-small" >
                <div class="row">
                    <a target="_blank" href="{% static 'documents/congreso/convocatoria/convocatoria_mesas_de_debate_congreso.pdf' %}">
                        <div class="col-sm-2">
                            <div class="square-button yellow">Convocatoria</div>
                        </div>
                    </a>
                    <a target="_blank" href="{% static 'documents/congreso/convocatoria/cartel.pdf' %}">
                        <div class="col-sm-2">
                            <div class="square-button green">Cartel</div>
                        </div>
                    </a>
                    <a target="_blank" href="{% static 'documents/congreso/convocatoria/triptico.pdf' %}">
                        <div class="col-sm-2">
                            <div class="square-button blue">Triptico</div>
                        </div>
                    </a>
                    <a target="_blank" href="{% static 'documents/congreso/convocatoria/programa_congreso.pdf' %}">
                        <div class="col-sm-3">
                            <div class="square-button purple">Programa - Conferencias</div>
                        </div>
                    </a>
                    <a target="_blank" href="{% static 'documents/congreso/convocatoria/programa_cursos_taller.pdf' %}">
                        <div class="col-sm-3">
                            <div class="square-button red">Programa - Cursos taller</div>
                        </div>
                    </a>
                </div>	
                <p class="margin-top-small">
                    Descarga el documento en PDF de tu interés.
                </p>

                <a href="{% url 'congreso:registro_congreso' %}">
                    <div class="col-sm-4 col-sm-offset-4">
                        <div class="square-button green-important main">
                            <strong>Regístrate al Congreso</strong></div>
                    </div>
                </a>
                <a href="{% url 'congreso:registro_mesas_debate' %}">
                    <div class="col-sm-4 col-sm-offset-4">
                        <div class="square-button green-important main">
                            <strong>Regístrate a Mesa de Debates</strong></div>
                    </div>
                </a>
                <a href="#" data-toggle="modal" data-target="#costsModal">
                    <div class="col-sm-2 col-sm-offset-5">
                        <div class="square-button red-important secundary">
                            <strong>Cuotas de recuperación</strong></div>
                    </div>
                </a>
            </div>	
        </div>	
    </div>

    <div class="container-fluid accented-container odd">
        <div class="container text-center">
            <p style="margin: 50px 0 20px; font-size: 17px;">
                El Instituto Tecnológico de Acapulco realizará este año la Semana Académica y Cultural,
                que tiene como propósito vincular a la comunidad Tecnológica académica, científica, empresarial
                y a la sociedad en general. Expertos profesionistas y académicos compartirán sus experiencias
                con ponencias magistrales en temas de interés nacional como es el ahorro de energía, nuevas tecnologías,
                desarrollo sustentable, innovación y competitividad, avances tecnológicos en la empresa, medios
                digitales y el marketing digital.
            </p>
        </div> 
    </div>

    <div class="container-fluid accented-container even">
        <div class="container text-center">
            <h2>CONFERENCISTAS MAGISTRALES</h2>
            {% if conferencistas %}
                <div class="row">
                    {% for conferencista in conferencistas %}
                    <div class="col-sm-4">
                        <a href="{% url 'congreso:conferencista' conferencista.slug%}">
                            <div class="thumbnail demo">

                                {% thumbnail conferencista.imagen "400x400" crop="center" as im %}
                                <img
                                    class="rounded-avatar-image"
                                    src="{{ im.url }}"
                                    alt="{{ conferencista.nombre }}"
                                    title="{{ conferencista.nombre }}" />
                                {% endthumbnail %}

                                <div class="caption speaker">
                                    <h5 class="text-center"><strong>{{ conferencista.nombre }}</strong></h5>
                                </div>
                            </div>
                        </a>
                    </div>
                    {% endfor %}
                </div>
            {% else %}
                No hay docentes que mostrar.
            {% endif %}
            <br>
        </div>	
    </div>	

    <div class="container-fluid accented-container odd">
        <div class="container text-center">
            <h2>CURSOS - TALLER</h2>
            {% if cursos %}
                <div class="row text-center">
                    {% for curso in  cursos %}
                    <div class="col-md-2">
                     <a href="{% url 'congreso:curso' curso.slug %}">
                        <div class="thumbnail demo conference-demo">
                        <span class="news-date"><h5>{{ curso.time|date:"d M " }}</h5></span>

                        {% thumbnail curso.imagen "300x300" crop="center" as im %}
                        <img class="course" src="{{ im.url }}" alt="" />
                        {% endthumbnail %}

                            <div class="caption">
                                <h5 class="text-center"><strong>{{ curso.nombre }}</strong></h5>
                            </div>

                        </div>
                        </a>
                    </div>
                    {% endfor %}
                </div>
                <div class="row">
                    <div class="col-md-3 col-md-offset-3">
                        <a href="{% url 'congreso:registro_curso' %}">
                            <div class="col-sm-12">
                                <div class="square-button green-important">Regístrate</div>
                            </div>
                        </a>
                    </div>
                    <div class="col-md-3">
                        <a href="{% url 'congreso:cursos' %}">
                            <div class="col-sm-12">
                                <div class="square-button purple">Ver todos</div>
                            </div>
                        </a>
                    </div>
                </div>	
            {% endif %}
        </div>	
    </div>	

    <!-- Modal -->
    <div class="modal fade" id="costsModal" tabindex="-1" role="dialog" aria-labelledby="costsModalLabel">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <h4 class="modal-title" id="costsModalLabel">Cuotas de recuperación</h4>
          </div>
          <div class="modal-body">
              <img src="{% static 'imagenes/congreso/costs.jpg' %}" alt="cuotas de recuperacion">
          </div>
          <div class="modal-footer">
            <button type="button" data-dismiss="modal" class="btn square-button purple">Cerrar</button>
          </div>
        </div>
      </div>
    </div>
    <!-- Modal -->

</div>
{% include 'congreso/partials/contact-sticky-button.html' %}
{% endblock%}

{% block scripts %}
    <script src="{% static 'js/custom.js' %}"></script>
{% endblock scripts %}